[package]
name = "kyopro-ratings"
version = "0.1.0"
authors = ["algon-320 <algon.0320@gmail.com>"]

[dependencies]
reqwest = "0.9.11"
scraper = "0.9.1"
hyper = "0.12"
serde_json = "1.0"
chrono = "0.4"